### ISSUE TITLE
兼容下拉刷新么

### ISSUE THREAD

**Issue by Licarey** [pengguanming/MiMusicBehavior#1]
你好 比如我把recycler改成下拉刷新的列表，不会有手势冲突吧

**Comment by pengguanming** [comment]
您好，以此项目为例，不知是否认真看的我的《浅析NestedScrolling嵌套滑动机制之基础篇》https://juejin.im/post/5ede31496fb9a047a226a44a
其实你将下拉刷新控件SwipeRefreshLayout包裹RecyclerView，当下拉RecyclerView时，滑动嵌套事件从最里层的view往外传递：RecyclerView->SwipeRefreshLayout->CoordinatorLayout->ContentBehavior，所以ContentBehavior最先处理这RecyclerView下拉，效果如下图：
https://gitee.com/pgm250/blog_img_bed/raw/master/issue/github_mimusic_issue.gif
只有ContentBehavior消费一段距离（即ContentBehavior下拉的极限）才会把滑动传给SwipeRefreshLayout，不知这是不是你要的效果。当然如果您SwipeRefreshLayout作为最层view把CoordinatorLayout包裹，这就会发生冲突，就必须覆写SwipeRefreshLayout的onStartNestedScroll()在更具业务放行下拉的事件。如果觉得文章对您有帮助，不妨点个赞吧。

**Comment by Licarey** [comment]
@pengguanming 多谢回复 Thanks♪(･ω･)ﾉ
