### ISSUE TITLE
快速向下滚动 头部会出现两次下拉

### ISSUE THREAD

**Issue by z876335662** [pengguanming/MiMusicBehavior#2]

**Comment by pengguanming** [comment]
您好，我这边试过快速向下滚动，没有出现头部两次下拉的情况哦，你可以录屏提供一下操作还原复现一下吗？因为有可能在向下滚动时误触到view导致头部两次下拉。

**Comment by z876335662** [comment]
我这边是用viewpager2 嵌套recycleview  能给个联系方式吗

**Comment by pengguanming** [comment]
QQ:740865629；申请注明：GitHub

**Comment by est7** [comment]
我试了下 samples,好像真有这个问题

https://github.com/user-attachments/assets/08e390c6-4739-4b5c-ab4b-36ce97a39c9a

**Comment by pengguanming** [comment]
这个周末得花时间解决一下这个bug，平时工作较忙，欢迎fork项目代码提交pr。
